### ISSUE TITLE
Error when building for android :app:transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by ziarno** [chetstone/react-native-palette#5]
I'm getting this error when trying to build for android:

```
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.221 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

I basically tried it on an empty React Native project:
```
react-native init test-palette
cd test-palette 
npm i react-native-palette
react-native link react-native-palette
react-native run-android
```

**Comment by stefankuburovic** [comment]
@ziarno 

I got same error, and I added this:

`multiDexEnabled true`  in 

`
defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
...
}
`
in android/build.gradle

then you should run command  `./gradlew clean` from android directory and after that if you get 
> java.util.zip.ZipException

you should add in build.gradle

`configurations {
        all*.exclude group: 'com.android.support', module: 'support-v4'
        all*.exclude group: 'com.android.support', module: 'support-annotations'
    }`

That helped me

**Comment by efkan** [comment]
I've just changed `appcompat` version as `v7:24.2.1` and it works.
Thanks..

**Comment by ziarno** [comment]
changing `appcompat` works, thanks guys!
